
format = """
[](mauve)\
$username\
[](bg:red fg:mauve)\
$directory\
[](fg:red bg:peach)\
$git_branch\
$git_status\
[](fg:peach bg:yellow)\
$c\
$crystal\
$dart\
$elixir\
$elm\
$erlang\
$golang\
$haskell\
$java\
$julia\
$kotlin\
$lua\
$nodejs\
$nim\
$php\
$python\
$ruby\
$rust\
$scala\
$swift\
$vlang\
[](fg:yellow bg:green)\
$docker_context\
[](fg:green bg:blue)\
$time\
[ ](fg:blue)\
"""

palette = "macchiato"

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:mauve fg:crust"
style_root = "bg:mauve fg:crust"
format     = '[ ]($style)' # $user or 

[directory]
style             = "bg:red fg:crust"
format            = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Desktop"   = " "
"Documents" = " "
"Downloads" = " "
"Music"     = " "
"Pictures"  = " "

# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style  = "bg:yellow fg:crust"
format = '[ $symbol ($version) ]($style)'

[crystal]
symbol = " "
style  = "bg:yellow fg:crust"
format = '[ $symbol ($version) ]($style)'

[dart]
symbol = "➵"
style  = "bg:yellow fg:crust"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style  = "bg:green fg:crust"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style  = "bg:yellow fg:crust"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style  = "bg:yellow fg:crust"
format = '[ $symbol ($version) ]($style)'

[erlang]
symbol = " "
style  = "bg:yellow fg:crust"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style  = "bg:#FCA17D fg:crust"
format = '[ $symbol $branch ]($style)'

[git_status]
style  = "bg:#FCA17D fg:crust"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style  = "bg:yellow fg:crust"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style  = "bg:yellow fg:crust"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style  = "bg:yellow fg:crust"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style  = "bg:yellow fg:crust"
format = '[ $symbol ($version) ]($style)'

[kotlin]
symbol = " "
style  = "bg:yellow fg:crust"
format = '[ $symbol ($version) ]($style)'

[lua]
symbol = " "
style  = "bg:yellow fg:crust"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style  = "bg:yellow fg:crust"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style  = "bg:yellow fg:crust"
format = '[ $symbol ($version) ]($style)'

[php]
symbol = " "
style  = "bg:yellow fg:crust"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = " "
style  = "bg:yellow fg:crust"
format = '[ $symbol ($version) ]($style)'

[ruby]
symbol = " "
style  = "bg:yellow fg:crust"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style  = "bg:yellow fg:crust"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = ""
style  = "bg:yellow fg:crust"
format = '[ $symbol ($version) ]($style)'

[swift]
symbol = "ﯣ "
style  = "bg:yellow fg:crust"
format = '[ $symbol ($version) ]($style)'

[vlang]
symbol = "V "
style  = "bg:yellow fg:crust"
format = '[ $symbol ($version) ]($style)'

[time]
disabled    = false
time_format = "%R" # Hour:Minute Format
style 	    = "bg:blue fg:crust"
format      = '[ ♥ $time ]($style)'

[palettes.macchiato]
rosewater = "#f4dbd6"
flamingo  = "#f0c6c6"
pink 	  = "#f5bde6"
mauve 	  = "#c6a0f6"
red	  = "#ed8796"
maroon	  = "#ee99a0"
peach 	  = "#f5a97f"
yellow 	  = "#eed49f"
green 	  = "#a6da95"
teal 	  = "#8bd5ca"
sky 	  = "#91d7e3"
sapphire  = "#7dc4e4"
blue 	  = "#8aadf4"
lavender  = "#b7bdf8"
text 	  = "#cad3f5"
subtext1  = "#b8c0e0"
subtext0  = "#a5adcb"
overlay2  = "#939ab7"
overlay1  = "#8087a2"
overlay0  = "#6e738d"
surface2  = "#5b6078"
surface1  = "#494d64"
surface0  = "#363a4f"
base 	  = "#24273a"
mantle 	  = "#1e2030"
crust 	  = "#181926"
